# Import json to save structured data into a .json file.
import json

# Import re to search text using regular expressions (patterns).
import re

# Import Path to check whether input/output files exist safely.
from pathlib import Path


# Create a function that extracts lines belonging to specific section headings.
def extract_section(lines, section_name):
    # Build a simple regex that matches the exact heading name (case-insensitive).
    heading_pattern = re.compile(rf"^{re.escape(section_name)}\s*$", re.IGNORECASE)

    # Define common section headings so we know when a section ends.
    all_headings = {"skills", "education", "experience"}

    # Track whether we are currently inside the requested section.
    in_section = False

    # Store all lines that belong to the requested section.
    collected = []

    # Loop through each line in the resume text.
    for line in lines:
        # Remove extra spaces around the line for easier matching.
        stripped = line.strip()

        # Skip empty lines to keep extracted data clean.
        if not stripped:
            continue

        # If this line matches the section heading, start collecting next lines.
        if heading_pattern.match(stripped):
            in_section = True
            continue

        # If we are in the section and hit another known heading, section is finished.
        if in_section and stripped.lower() in all_headings:
            break

        # If we are currently inside the section, collect the line.
        if in_section:
            collected.append(stripped)

    # Return collected lines (empty list if section was not found).
    return collected


# Create the main function to organize script steps clearly.
def main():
    # Define the input text file path generated by the previous parser step.
    input_path = Path("resume_text.txt")

    # Define the output JSON file path for structured resume data.
    output_path = Path("resume_data.json")

    # Stop early with a helpful message if the input file is missing.
    if not input_path.exists():
        print("Error: 'resume_text.txt' was not found in this folder.")
        print("Please generate it first, then run this script again.")
        return

    # Read all text content from resume_text.txt using UTF-8 encoding.
    raw_text = input_path.read_text(encoding="utf-8")

    # Split text into lines and strip surrounding spaces from each line.
    lines = [line.strip() for line in raw_text.splitlines()]

    # Keep only non-empty lines to simplify first-line (name) detection.
    non_empty_lines = [line for line in lines if line]

    # Assume the name is the first non-empty line; if unavailable, set as Not found.
    name = non_empty_lines[0] if non_empty_lines else "Not found"

    # Regex pattern for common email formats (e.g., user@example.com).
    email_pattern = re.compile(r"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}")

    # Find first email match in the full text, if any.
    email_match = email_pattern.search(raw_text)

    # Store matched email text or a fallback value.
    email = email_match.group(0) if email_match else "Not found"

    # Regex pattern for international phone numbers.
    # Supports optional +country code, spaces, dashes, and parentheses.
    phone_pattern = re.compile(r"\+?\d[\d\s().-]{7,}\d")

    # Find first phone number match in the full text, if any.
    phone_match = phone_pattern.search(raw_text)

    # Store matched phone text or a fallback value.
    phone = phone_match.group(0) if phone_match else "Not found"

    # Extract list of lines under the Skills heading.
    skills = extract_section(lines, "Skills")

    # Extract list of lines under the Education heading.
    education = extract_section(lines, "Education")

    # Extract list of lines under the Experience heading.
    experience = extract_section(lines, "Experience")

    # Build one dictionary with all structured resume fields.
    resume_data = {
        "name": name,
        "email": email,
        "phone": phone,
        "skills": skills if skills else ["Section not found or empty"],
        "education": education if education else ["Section not found or empty"],
        "experience": experience if experience else ["Section not found or empty"],
    }

    # Convert dictionary to pretty JSON text for easy reading.
    pretty_json = json.dumps(resume_data, indent=4, ensure_ascii=False)

    # Print the structured result clearly in the terminal.
    print("\n===== STRUCTURED RESUME DATA START =====\n")
    print(pretty_json)
    print("\n===== STRUCTURED RESUME DATA END =====\n")

    # Save structured JSON into resume_data.json.
    output_path.write_text(pretty_json, encoding="utf-8")

    # Confirm where output was saved.
    print(f"Success: structured data saved to '{output_path}'.")


# Run main() only when the file is executed directly.
if __name__ == "__main__":
    # Start the resume structuring workflow.
    main()
